#
# Module manifest for module 'WingetElevate'
#
# Generated by: RayG
#
# Generated on: 13/03/2026
#

@{
    RootModule        = 'WingetElevate.psm1'
    ModuleVersion     = '0.1'
    GUID              = '3f7e8b21-0c45-4d9a-b6f2-1e8a5c3d9071'
    Author            = 'RayG'
    CompanyName       = 'RayG'
    Copyright         = '(c) 2026 RayG. All rights reserved.'
    Description       = 'Transparent winget elevation wrapper for non-admin users. Workaround for winget error 0x80070005 on standard user accounts using a persistent NamedPipe elevated session.'
    PowerShellVersion = '5.0'
    RequiredModules   = @()
    FunctionsToExport = @('winget')
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
    PrivateData       = @{
        PSData = @{
            Tags         = @('winget', 'elevation', 'UAC', 'Windows', 'NamedPipe', '0x80070005')
            ProjectUri   = 'https://github.com/RG255/WingetElevate'
            ReleaseNotes = 'Initial release.'
        }
    }
}
